### ISSUE TITLE
Episerver DBLOcalixation Upgrade Issue

### ISSUE THREAD

**Issue by coolgal1980** [valdisiljuconoks/LocalizationProvider#187]
There was another upgrade of DBLocalization Package and it required to upgrade the Localization Package and it caused these issues:

Follows were the upgrades:
DbLocalizationProvider.AdminUI.EPiServer.6.0.2 -> DbLocalizationProvider.AdminUI.EPiServer.6.1.0
DbLocalizationProvider.EPiServer.6.0.2 -> DbLocalizationProvider.EPiServer.6.1.0
LocalizationProvider.AspNet.6.0.2 -> LocalizationProvider.AspNet.6.1.0
LocalizationProvider.6.0.2 -> LocalizationProvider.6.1.0
LocalizationProvider.Abstractions.6.0.2 -> LocalizationProvider.Abstractions.6.1.0
 
Errors in the backend:
2020-06-10 15:53:09,265 [1] ERROR EPiServer.Framework.Initialization.InitializationEngine: Initialize action failed for 'Initialize on class EPiServer.Forms.EditView.InitializationModule, EPiServer.Forms.UI, Version=4.29.0.0, Culture=neutral, PublicKeyToken=8fe83dea738b45b7'
System.MissingMethodException: Method not found: 'System.Collections.Generic.IReadOnlyCollection`1<System.Globalization.CultureInfo> DbLocalizationProvider.ConfigurationContext.get_FallbackCultures()'.
   at DbLocalizationProvider.Storage.SqlServer.GetTranslationHandler.Execute(Query query)
   at DbLocalizationProvider.Queries.Internal.QueryHandlerWrapper`2.Execute(IQuery`1 message)
   at DbLocalizationProvider.IQueryExtensions.Execute[TResult](IQuery`1 query)
   at DbLocalizationProvider.EPiServer.DatabaseLocalizationProvider.GetString(String originalKey, String[] normalizedKey, CultureInfo culture)
   at EPiServer.Framework.Localization.ProviderBasedLocalizationService.LoadString(String[] normalizedKey, String originalKey, CultureInfo culture)
   at EPiServer.Framework.Localization.LocalizationService.TryGetStringByCulture(String originalKey, String[] normalizedKey, CultureInfo culture, CultureInfo fallbackCulture, String& localizedString)
   at EPiServer.Framework.Localization.LocalizationService.GetStringByCulture(String resourceKey, FallbackBehaviors fallbackBehavior, String fallback, CultureInfo culture)
   at EPiServer.Framework.Localization.LocalizationService.GetStringByCulture(String resourceKey, FallbackBehaviors fallbackBehavior, CultureInfo culture)
   at EPiServer.Forms.EditView.InitializationModule.SetupFormContainerProperties()
   at EPiServer.Forms.EditView.InitializationModule.Initialize(InitializationEngine context)
   at EPiServer.Framework.Initialization.Internal.ModuleNode.<>c__DisplayClass2_0.<Initialize>b__0()
   at EPiServer.Framework.Initialization.Internal.ModuleNode.Execute(Action a, String key)
   at EPiServer.Framework.Initialization.Internal.ModuleNode.Initialize(InitializationEngine context)
   at EPiServer.Framework.Initialization.InitializationEngine.InitializeModules()
System.MissingMethodException: Method not found: 'System.Collections.Generic.IReadOnlyCollection`1<System.Globalization.CultureInfo> DbLocalizationProvider.ConfigurationContext.get_FallbackCultures()'.
   at DbLocalizationProvider.Storage.SqlServer.GetTranslationHandler.Execute(Query query)
   at DbLocalizationProvider.Queries.Internal.QueryHandlerWrapper`2.Execute(IQuery`1 message)
   at DbLocalizationProvider.IQueryExtensions.Execute[TResult](IQuery`1 query)
   at DbLocalizationProvider.EPiServer.DatabaseLocalizationProvider.GetString(String originalKey, String[] normalizedKey, CultureInfo culture)
   at EPiServer.Framework.Localization.ProviderBasedLocalizationService.LoadString(String[] normalizedKey, String originalKey, CultureInfo culture)
   at EPiServer.Framework.Localization.LocalizationService.TryGetStringByCulture(String originalKey, String[] normalizedKey, CultureInfo culture, CultureInfo fallbackCulture, String& localizedString)
   at EPiServer.Framework.Localization.LocalizationService.GetStringByCulture(String resourceKey, FallbackBehaviors fallbackBehavior, String fallback, CultureInfo culture)
   at EPiServer.Framework.Localization.LocalizationService.GetStringByCulture(String resourceKey, FallbackBehaviors fallbackBehavior, CultureInfo culture)
   at EPiServer.Forms.EditView.InitializationModule.SetupFormContainerProperties()
   at EPiServer.Forms.EditView.InitializationModule.Initialize(InitializationEngine context)
   at EPiServer.Framework.Initialization.Internal.ModuleNode.<>c__DisplayClass2_0.<Initialize>b__0()
   at EPiServer.Framework.Initialization.Internal.ModuleNode.Execute(Action a, String key)
   at EPiServer.Framework.Initialization.Internal.ModuleNode.Initialize(InitializationEngine context)
   at EPiServer.Framework.Initialization.InitializationEngine.InitializeModules()
2020-06-10 15:56:16,866 [1] ERROR EPiServer.Framework.Initialization.InitializationEngine: Initialize action failed for 'Initialize on class EPiServer.Forms.EditView.InitializationModule, EPiServer.Forms.UI, Version=4.29.0.0, Culture=neutral, PublicKeyToken=8fe83dea738b45b7'
System.MissingMethodException: Method not found: 'System.Collections.Generic.IReadOnlyCollection`1<System.Globalization.CultureInfo> DbLocalizationProvider.ConfigurationContext.get_FallbackCultures()'.
   at DbLocalizationProvider.Storage.SqlServer.GetTranslationHandler.Execute(Query query)
   at DbLocalizationProvider.Queries.Internal.QueryHandlerWrapper`2.Execute(IQuery`1 message)
   at DbLocalizationProvider.IQueryExtensions.Execute[TResult](IQuery`1 query)
   at DbLocalizationProvider.EPiServer.DatabaseLocalizationProvider.GetString(String originalKey, String[] normalizedKey, CultureInfo culture)
   at EPiServer.Framework.Localization.ProviderBasedLocalizationService.LoadString(String[] normalizedKey, String originalKey, CultureInfo culture)
   at EPiServer.Framework.Localization.LocalizationService.TryGetStringByCulture(String originalKey, String[] normalizedKey, CultureInfo culture, CultureInfo fallbackCulture, String& localizedString)
   at EPiServer.Framework.Localization.LocalizationService.GetStringByCulture(String resourceKey, FallbackBehaviors fallbackBehavior, String fallback, CultureInfo culture)
   at EPiServer.Framework.Localization.LocalizationService.GetStringByCulture(String resourceKey, FallbackBehaviors fallbackBehavior, CultureInfo culture)
   at EPiServer.Forms.EditView.InitializationModule.SetupFormContainerProperties()
   at EPiServer.Forms.EditView.InitializationModule.Initialize(InitializationEngine context)
   at EPiServer.Framework.Initialization.Internal.ModuleNode.<>c__DisplayClass2_0.<Initialize>b__0()
   at EPiServer.Framework.Initialization.Internal.ModuleNode.Execute(Action a, String key)
   at EPiServer.Framework.Initialization.Internal.ModuleNode.Initialize(InitializationEngine context)
   at EPiServer.Framework.Initialization.InitializationEngine.InitializeModules()
System.MissingMethodException: Method not found: 'System.Collections.Generic.IReadOnlyCollection`1<System.Globalization.CultureInfo> DbLocalizationProvider.ConfigurationContext.get_FallbackCultures()'.
   at DbLocalizationProvider.Storage.SqlServer.GetTranslationHandler.Execute(Query query)
   at DbLocalizationProvider.Queries.Internal.QueryHandlerWrapper`2.Execute(IQuery`1 message)
   at DbLocalizationProvider.IQueryExtensions.Execute[TResult](IQuery`1 query)
   at DbLocalizationProvider.EPiServer.DatabaseLocalizationProvider.GetString(String originalKey, String[] normalizedKey, CultureInfo culture)
   at EPiServer.Framework.Localization.ProviderBasedLocalizationService.LoadString(String[] normalizedKey, String originalKey, CultureInfo culture)
   at EPiServer.Framework.Localization.LocalizationService.TryGetStringByCulture(String originalKey, String[] normalizedKey, CultureInfo culture, CultureInfo fallbackCulture, String& localizedString)
   at EPiServer.Framework.Localization.LocalizationService.GetStringByCulture(String resourceKey, FallbackBehaviors fallbackBehavior, String fallback, CultureInfo culture)
   at EPiServer.Framework.Localization.LocalizationService.GetStringByCulture(String resourceKey, FallbackBehaviors fallbackBehavior, CultureInfo culture)
   at EPiServer.Forms.EditView.InitializationModule.SetupFormContainerProperties()
   at EPiServer.Forms.EditView.InitializationModule.Initialize(InitializationEngine context)
   at EPiServer.Framework.Initialization.Internal.ModuleNode.<>c__DisplayClass2_0.<Initialize>b__0()
   at EPiServer.Framework.Initialization.Internal.ModuleNode.Execute(Action a, String key)
   at EPiServer.Framework.Initialization.Internal.ModuleNode.Initialize(InitializationEngine context)
   at EPiServer.Framework.Initialization.InitializationEngine.InitializeModules()

**Comment by valdisiljuconoks** [comment]
Hi,

Are you sure that you have clean bin/ directory and having correct versions of .dll files there?

**Comment by valdisiljuconoks** [comment]
What about upgrading also `DbLocalizationProvider.Storage.SqlServer` ?

**Comment by valdisiljuconoks** [comment]
I'll change dependencies for other packages as well to mitigate this issue. By upgrading one of the package, related location provider packages will upgrade also.

**Comment by coolgal1980** [comment]
I did the upgrade again today:
DbLocalizationProvider.AdminUI.EPiServer.6.1.0 -> DbLocalizationProvider.AdminUI.EPiServer.6.2.0
DbLocalizationProvider.EPiServer.6.1.0 -> DbLocalizationProvider.EPiServer.6.2.0
LocalizationProvider.AspNet.6.1.0 -> LocalizationProvider.AspNet.6.2.0
LocalizationProvider.6.1.0 -> LocalizationProvider.6.2.0
LocalizationProvider.Abstractions.6.1.0 -> LocalizationProvider.Abstractions.6.2.0
And then ran into an error again. Then I did the following upgrade as well:
LocalizationProvider.Storage.SqlServer.6.1.0 -> LocalizationProvider.Storage.SqlServer.6.2.0

I thought you would be adding this as a dependency: LocalizationProvider.Storage.SqlServer.6.1.0 -> LocalizationProvider.Storage.SqlServer.6.2.0 
Just wanted to check if you got a chance to do that @valdisiljuconoks ?

**Comment by valdisiljuconoks** [comment]
Hi,

Sorry for trouble you have. This will be properly fixed in coming versions.
