### ISSUE TITLE
 Incorrect syntax near ')'.  

### ISSUE THREAD

**Issue by gatisb** [valdisiljuconoks/LocalizationProvider#274]
Adding `RenamedResource` when moving resource class around
```c#
namespace Geta.__A.Domain.Features.Orders
{
    [LocalizedResource]
    [RenamedResource("Resources", OldNamespace = "__B.Domain.Features.Orders")]
    public static class Resources
    {
``` 
leads to:
```c#
[2023-12-20 09:12:01] crit: Microsoft.AspNetCore.Hosting.Diagnostics[6]                                              
      Application startup exception                                                                                  
      System.AggregateException: One or more errors occurred. (One or more errors occurred. (Incorrect syntax near ')'.
      Incorrect syntax near ')'.                                                                                       
      Incorrect syntax near ')'.                                                                                       
      Incorrect syntax near ')'.                                                                                       
      Incorrect syntax near ')'.                                                                                       
      Incorrect syntax near ')'.                                                                                       
      Incorrect syntax near ')'.                                                                                       
      Incorrect syntax near ')'.                                                                                       
      Incorrect syntax near ')'.                                                                                       
      Incorrect syntax near ')'.
      Incorrect syntax near ')'.
      Incorrect syntax near ')'.))
       ---> System.AggregateException: One or more errors occurred. (Incorrect syntax near ')'.
      Incorrect syntax near ')'.
      Incorrect syntax near ')'.
      Incorrect syntax near ')'.
      Incorrect syntax near ')'.
      Incorrect syntax near ')'.
      Incorrect syntax near ')'.
      Incorrect syntax near ')'.
      Incorrect syntax near ')'.
      Incorrect syntax near ')'.
      Incorrect syntax near ')'.
      Incorrect syntax near ')'.)
       ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near ')'.
      Incorrect syntax near ')'.
      Incorrect syntax near ')'.
      Incorrect syntax near ')'.
      Incorrect syntax near ')'.
      Incorrect syntax near ')'.
      Incorrect syntax near ')'.
      Incorrect syntax near ')'.
      Incorrect syntax near ')'.
      Incorrect syntax near ')'.
      Incorrect syntax near ')'.
      Incorrect syntax near ')'.
         at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
         at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
         at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite)
         at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
         at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
         at DbLocalizationProvider.Storage.SqlServer.ResourceRepository.<>c__DisplayClass16_0.<RegisterDiscoveredResources>b__0(IEnumerable`1 group)
         at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
      --- End of stack trace from previous location ---
         at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
         at System.Threading.Tasks.TaskReplicator.Replica.Execute()
      ClientConnectionId:f5889f37-6598-413c-994f-56b99f70d247
      Error Number:102,State:1,Class:15
         --- End of inner exception stack trace ---
         at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
         at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFi
nally)
      --- End of stack trace from previous location ---
         at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFi
nally)
         at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
         at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
         at DbLocalizationProvider.Storage.SqlServer.ResourceRepository.RegisterDiscoveredResources(ICollection`1 discoveredResources, IEnumerable`1 allResources, Boolean flexibleRefactoringMode)
         at DbLocalizationProvider.Sync.Synchronizer.<>c__DisplayClass13_0.<Execute>b__0()
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
      --- End of stack trace from previous location ---
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
         --- End of inner exception stack trace ---
         at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
         at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
         at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
      --- End of stack trace from previous location ---
         at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
         at DbLocalizationProvider.Sync.Synchronizer.Execute(ICollection`1 discoveredResources, ICollection`1 discoveredModels, Boolean flexibleRefactoringMode)
         at DbLocalizationProvider.Sync.Synchronizer.DiscoverReadMerge()
         at DbLocalizationProvider.Sync.Synchronizer.SyncResources(Boolean registerResources)
         at DbLocalizationProvider.AspNetCore.IServiceProviderExtensions.UseDbLocalizationProvider(IServiceProvider serviceFactory)
         at DbLocalizationProvider.AspNetCore.IApplicationBuilderExtensions.UseDbLocalizationProvider(IApplicationBuilder builder)
         at Geta.__A.Web.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in C:\projects\geta-p\sub\geta-__A\src\Geta.__A.Web\Startup.cs:line 348
         at Geta.P.Web.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in C:\projects\geta-p\src\Geta.P.Web\Startup.cs:line 34
         at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
         at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
         at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
         at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
         at EPiServer.Find.FindStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
         at EPiServer.Cms.UI.Admin.Internal.RegisterDefaultCultureMiddlewareStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
         at EPiServer.Cms.Shell.UI.Internal.ErrorsStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
         at EPiServer.Shell.UI.Messaging.WebSocketsStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
         at EPiServer.Shell.Modules.Internal.ReadonlyDatabaseStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
         at EPiServer.Middleware.InitializationStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
         at EPiServer.Framework.DependencyInjection.Internal.InitializationStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
         at EPiServer.Forms.FormsPublicStaticFileStartupFilter.<>c__DisplayClass1_0.<Configure>b__0(IApplicationBuilder app)
         at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)

``` 

in version 7.5.1

**Comment by valdisiljuconoks** [comment]
look for 7.5.2
