### ISSUE TITLE
Unable to find a module by assembly 'DbLocalizationProvider.AdminUI.EPiServer'

### ISSUE THREAD

**Issue by stefanolsen** [valdisiljuconoks/LocalizationProvider#313]
Using this module on a CMS 12 site, I see the below exception logged when browsing the CMS UI.

```
Failed to add menu item
System.ArgumentException: Unable to find a module by assembly 'DbLocalizationProvider.AdminUI.EPiServer, Version=8.1.0.0, Culture=neutral, PublicKeyToken=e24b5062d4cb23b0' (Parameter 'moduleAssembly')
   at EPiServer.Shell.Paths.ToResource(Assembly moduleAssembly, String moduleRelativeResourcePath)
   at DbLocalizationProvider.AdminUI.EPiServer.MenuProvider.GetMenuItems()
   at EPiServer.Shell.Navigation.MenuAssembler.<>c.<GetMenuItems>b__8_1(IMenuProvider m)
```

The NuGet package (version 8.1.0) is installed and the services are registered in Startup. The folder `AddOn.Episerver.Settings` is present in `/modules/` and contains a ZIP-file.

It looks like the module is not present in ModuleTable.

Is there some registration I might have missed?

**Comment by valdisiljuconoks** [comment]
Please open if this is still relevant
